### ISSUE TITLE
Inconsistent resize button hover effect in Excalidraw

### ISSUE THREAD

**Issue by manaver** [bric3/excalidraw-jetbrains-plugin#129]
When attempting to resize objects in Excalidraw, I have noticed that the resize button hover effect can be inconsistent and difficult to use. Specifically, when hovering over the object resize button, it is not always selected, and the cursor does not smoothly transition from the pointer cursor to the stretch cursor that is used for resizing. This can make it difficult to accurately resize objects and can impact the overall user experience of Excalidraw.

One possible solution to this issue would be to improve the design or functionality of the resize button hover effect to make it more consistent and user-friendly. This could involve changes to the visual appearance of the button or adjustments to the way the hover effect is triggered. Overall, I believe that addressing this issue could significantly improve the usability and accessibility of Excalidraw for users who need to resize objects frequently.

https://user-images.githubusercontent.com/78682260/222983698-8823d830-cbe5-4c69-adf5-a9b8fda3d295.mp4

**Comment by bric3** [comment]
I believe you should report this to [Excalidraw](https://github.com/excalidraw/excalidraw) project directly. This code base "merely" embed an offline excalidraw version.

**Comment by bric3** [comment]
I'm closing this for now as I'm not part of excalidraw project.
