### ISSUE TITLE
White Background for Dracula 

### ISSUE THREAD

**Issue by kabronkline** [bric3/excalidraw-jetbrains-plugin#133]
Is there anyway I can have the plugin create drawings such that the background is white and the lines/texts are black by default while in dracula mode? When I switch appearance in IntelliJ to other appearances I get the desired display of newly created Excalidraws. Also when I open an existing Excalidraw drawing that was drawn with a white background and black lines/texts the plugin is displaying it incorrectly with black background and white lines/text again only in Dracula mode.

**Comment by bric3** [comment]
Note that Excalidraw supports the prefered scheme, meaning the sketch should changes colors when the browser color changes. This plugin actually relies on the same mechanism.

For forcing the colors it should be done in #85. However this version wasn't released, as I had some issues tackling racing conditions, and kinda let this project on the side for a while.

**Comment by bric3** [comment]
So there are two things to distinguish, 

1. the display theme
2. the saved file

When the file is an excalidraw (JSON) file, in theory this shouldn't matter as the file adapts to the current theme.

However when exported as an image (with an embedded scene), the display theme toggle does not matter, but the save light dark mode matter.

This should allow to handle things in your case.

Should be released with #194

**Comment by bric3** [comment]
If the new behavior does not work, maybe re-open a new issue with new UX suggestion based on 0.4.0.

Thank you very much for the feedback.
