### ISSUE TITLE
Publish newest version to matketplace

### ISSUE THREAD

**Issue by samoylovfp** [bric3/excalidraw-jetbrains-plugin#176]
The version published in the JetBrains marketplace is 2 years old at this point and diagrams made in the newest excalidraw tool, are opened weirdly by the plugin, for example text on top of the arrows becomes disconnected. As far as I understand the current master version has some improvements to this situation.

Would be nice to have the newest version published to the JetBrains marketplace for ease of installation.

Thanks for working on this!

**Comment by bric3** [comment]
I agree, I'll try to find some time to fix some race condition with the JCef browser.
In doing so I'll probably update the baseline of this plugin (2023.1 or 2023.2)
