### ISSUE TITLE
Scratch file is deleted when closed without warning

### ISSUE THREAD

**Issue by marcphilipp** [bric3/excalidraw-jetbrains-plugin#22]
When creating a `<name>.excalidraw` Scratch file, it is automatically deleted when closing. Instead, it should be persisted like a regular Scratch file.

**Comment by bric3** [comment]
Hi, sorry for replying that late.
Also thanks for reaching out.


I never tried scratch file. It should definitely be something that needs to be supported.

**Comment by bric3** [comment]
The new saving routines (not yet released) works better, but I still have some issues.

**Comment by bric3** [comment]
It doesn't seem to happen anymore with the new engine.

**Comment by marcphilipp** [comment]
The scratch file is no longer deleted but the changes are not saved for me.

**Comment by bric3** [comment]
Are you using the latest code on master?

**Comment by marcphilipp** [comment]
Ah, no, sorry, this was with 0.3.2.
