### ISSUE TITLE
double-click behaviour differs from the web version

### ISSUE THREAD

**Issue by lestephane** [bric3/excalidraw-jetbrains-plugin#56]
When I double click on a box shape in the web version, I get to add a label that is associated with the shape.
When I double click on a box shape in the plugin tab, a new text label is added where I double clicked, which is not associated with the shape, and will not move with it.

**Comment by bric3** [comment]
It may be related to the Excalidraw version, web version is continuously deployed, while my plugin is actually packaging Excalidraw in order to be able to work offline.

**Comment by bric3** [comment]
Should be fixed in the next release
